openapi: 3.0.3
info:
  title: Customer Service
  description: |-
    This service provides all necessary methods for creating and managing customers.
  version: 0.1.0
paths:
  /customer:
    post:
      summary: create a new customer
      description: Returns the customer ID.
      operationId: createCustomer
      requestBody:
        description: create a new customer
        content:
          application/json:
            schema:
              type: object
              properties:
                idempotencyKey:
                  type: string
                  example: 'eerr-ddfr-2232'
                firstname:
                  type: string
                  example: 'Max'
                lastname:
                  type: string
                  example: 'Mustermann'
                credit:
                  type: number
                  example: 500
 
      responses:
        '200':
          description: The customer ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                example:
                  - customerId: "1234ed2"
                  
        '400':
          description: Cannot accept the customer.
    get:
      summary: get list of customer IDs
      description: Returns a list containing the ID of each customer
      operationId: getCustomerIds
            
      responses:
        '200':
          description: The list containing the ID of each customer
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string  
                  example: "639b53b1b5cbbc71012f4084"
                      
  /customer/byid/{customerId}:        
    get:
      summary: get customer by ID
      description: Returns the corresponding customer object.
      operationId: getCustomerById
      parameters: 
        - name: customerId
          in: path
          description: ID of the customer
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: The corresponding customer.
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstname:
                    type: string
                    example: 'Max'
                  lastname:
                    type: string
                    example: 'Mustermann'
        
        '400': 
          description: customer not found  

    delete:
      summary: delete customer
      description: deletes the corresponding customer object.
      operationId: deleteCustomer
      parameters: 
        - name: customerId
          in: path
          description: ID of the customer
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: The corresponding customer was deleted.

        '400': 
          description: bad request  

        '404': 
          description: customer not found  
    
  /customer/credit:
    post:
      summary: change the credit of the customer
      operationId: changeCustomerCredit
      requestBody:
        description: increments the customers credit
        content:
          application/json:
            schema:
              type: object
              properties:
                idempotencyKey:
                  type: string
                  example: 'eerr-ddfr-2232'
                customerId:
                  type: string
                  example: '334e54wr53'
                increment:
                  type: number
                  example: -70

      responses:
        '200':
          description: The credit was changed.

        '400': 
          description: bad request  

  /customer/info:
    get:
      summary: get service related informations
      description: Returns the version, url path prefix and startup time of the service. This path is also used to satifsy the health probe of the Azure Application Gateway.
      operationId: getServiceInfo
      responses:
        '200':
          description: An object containing the version and start time of the service.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  pathPrefix:
                    type: string
                  start:
                    type: string
                example:
                  - version: "1.0.0"
                    pathPrefix: '/product'
                    start: "2022-11-28T18:21:34.846Z"
        
  
  