openapi: 3.0.3
info:
  title: Order Service
  description: |-
    This service provides all necessary methods for creating and managing orders.
  version: 0.1.0
paths:
  /order:
    post:
      summary: create a new order
      description: Returns the order ID.
      operationId: createOrder
      requestBody:
        description: create a new order
        content:
          application/json:
            schema:
              type: object
              properties:
                idempotencyKey:
                  type: string
                  example: '5555f035529e1e68265bb111'
                customerId:
                  type: string
                  example: '643ef035529e1e68265bb1ab'
                cartContent:
                  type: array
                  items: 
                    type: object
                  properties:
                    productId: 
                      type: string
                    quantity: 
                      type: integer
                  example:
                    - productId: 'e43ef035529eee68265bb123'
                      quantity: 5
 
      responses:
        '202':
          description: Identified the order to be the first one with the provided idempotencyKey and accepted the order, which will get processed asynchronously.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 'abcef035529eee68265bbe43'

        '200':
          description: The provided idempotencyKey was already used and the order is the same.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 'abcef035529eee68265bbe43'
                  
        '400':
          description: Cannot accept the order.

    get:
      summary: get list of order IDs
      description: Returns a list containing the ID of each order
      operationId: getOrderIds
            
      responses:
        '200':
          description: The list containing the ID of each order
          content:
            application/json:
              schema:
                type: array
                items: 
                  type: string
                  example: 'abcef035529eee68265bbe43'

  /order/byid/{orderId}:        
    get:
      summary: get order by ID
      description: Returns the corresponding order object.
      operationId: getOrderById
      parameters: 
        - name: orderId
          in: path
          description: ID of the order
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: The corresponding order.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: '639b53b1b5cbbc71012f4084'
                  idempotencyKey:
                    type: string
                    example: '5bcef035529eee68265b5e45'
                  cartContent:
                    type: array
                    items: 
                      type: object
                    properties:
                      productId: 
                        type: string
                      quantity: 
                        type: integer
                    example:
                      - productId: '33cef035529efe68265b5ee5'
                        quantity: 5
                  type:
                    type: string
                    example: 'entity'
                  creation:
                    type: number
                    example: 1672938959291
                  lastModification:
                    type: number
                    example: 1672938959291
        
        '404': 
          description: order not found  
    
    delete:
      summary: delete order
      description: deletes the corresponding order object.
      operationId: deleteOrder
      parameters: 
        - name: orderId
          in: path
          description: ID of the order
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: The corresponding order was deleted.

        '400': 
          description: bad request  

        '404': 
          description: order not found  

  /order/info:
    get:
      summary: get product related informations
      description: Returns the version, url path prefix and startup time of the service. This path is also used to satifsy the health probe of the Azure Application Gateway.
      operationId: getServiceInfo
      responses:
        '200':
          description: An object containing the version and start time of the service.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: '1.0.0'
                  pathPrefix:
                    type: string
                    example: '/order'
                  start:
                    type: string
                    example: '2022-11-28T18:21:34.846Z'
